# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "Hi I'm Asaph"
tagline:          ''
description:      'I explore and build.'
url:              http://asaphyuan.com

author:
  name:           'Asaph Yuan'
  url:            http://asaphyuan.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/asaphy/personalwebsite