title: Hello, world! I'm Asaph Yuan
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Asaph Yuan # add your name
author-img: me.png # add your photo
about-author: Follower of Jesus.<br/> Son, brother, friend. Engineer. Musician. Writer.  # add description
facebook: asaph.yuan # add your Facebook handle
github: asaphy # add your Github handle
linkedin: asaphyuan # add your Linkedin handle
email: asaph.yuan@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
